FROM python:3.13.7-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

WORKDIR /app

# кэшируем зависимости отдельным слоем
COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen --no-install-project || uv sync --no-install-project

COPY . .

RUN uv sync --frozen || uv sync

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "mona_core.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]