"""initial migration

Revision ID: f6a881ec3876
Revises: 
Create Date: 2026-07-13 01:41:29.435487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a881ec3876'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('ram', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomalies_device_timestamp', 'anomalies', ['device', 'timestamp'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('ram', sa.Float(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_device_timestamp', 'metrics', ['device', 'timestamp'], unique=False)
    op.create_table('trained_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_data', sa.LargeBinary(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('trained_by', sa.String(), nullable=False),
    sa.Column('points_count', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.DateTime(), nullable=False),
    sa.Column('period_to', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('trained_models')
    op.drop_index('idx_metrics_device_timestamp', table_name='metrics')
    op.drop_table('metrics')
    op.drop_table('devices')
    op.drop_index('idx_anomalies_device_timestamp', table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
