# FROM python:3.13 AS builder

# RUN apt-get update \
#     && apt-get upgrade -y \
#     && rm -rf /var/lib/apt/lists/*

# COPY docker/requirements_celery.txt .
# RUN pip install --no-cache-dir -r requirements_celery.txt

# FROM python:3.13-slim
# RUN apt-get update \
#     && apt-get upgrade -y \
#     && rm -rf /var/lib/apt/lists/*
# RUN addgroup --system --gid 10001 app && adduser --system --uid 10001 --ingroup app app
# COPY --from=builder /usr/local /usr/local
# COPY . /app
# WORKDIR /app

# ENV PYTHONPATH=/app/mona_core

# RUN chown -R app:app /app
# USER app
# HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 CMD python -c "import shutil; import subprocess; import sys; sys.exit(0 if shutil.which('celery') else 1)" || exit 1
# CMD ["celery", "-A", "celery_conf", "worker", "--loglevel=info"]

FROM python:3.13 AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/opt/venv

WORKDIR /app
COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-default-groups --group worker --no-install-project

RUN uv pip install --python /opt/venv/bin/python --no-cache \
    --upgrade "setuptools>=78.1.1" "msgpack>=1.2.1"

FROM python:3.13-slim

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*


RUN addgroup --system --gid 10001 app && adduser --system --uid 10001 --ingroup app app
COPY . /app
WORKDIR /app

COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONPATH=/app/mona_core

RUN chown -R app:app /app
USER app
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 CMD python -c "import shutil; import subprocess; import sys; sys.exit(0 if shutil.which('celery') else 1)" || exit 1
CMD ["celery", "-A", "celery_conf", "worker", "--loglevel=info"]
