FROM python:3.11 AS builder
WORKDIR /app
COPY docker/requirements_fastapi.txt .
RUN pip install --no-cache-dir -r requirements_fastapi.txt

FROM python:3.11-slim
COPY --from=builder /usr/local /usr/local
COPY . /app
WORKDIR /app
CMD ["uvicorn", "mona_core.main:app", "--host", "0.0.0.0", "--port", "80"]