FROM python:3.11
WORKDIR /app
COPY docker/requirements_fastapi.txt .
RUN pip install -r requirements_fastapi.txt
COPY mona_core/ ./mona_core/
CMD ["uvicorn", "mona_core.main:app", "--host", "0.0.0.0", "--port", "80"]