FROM python:3.11 AS builder
COPY docker/requirements_celery.txt .
RUN pip install --no-cache-dir -r requirements_celery.txt

FROM python:3.11-slim
COPY --from=builder /usr/local /usr/local
COPY . /app
WORKDIR /app

ENV PYTHONPATH=/app/mona_core

CMD ["celery", "-A", "celery_conf", "worker", "--loglevel=info"]