FROM python:3.13 AS builder

RUN apt-get update \
    && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*

COPY docker/requirements_celery.txt .
RUN pip install --no-cache-dir -r requirements_celery.txt

FROM python:3.13-slim
# RUN addgroup --system app && adduser --system --ingroup app app
RUN addgroup --system --gid 10001 app && adduser --system --uid 10001 --ingroup app app
COPY --from=builder /usr/local /usr/local
COPY . /app
WORKDIR /app

ENV PYTHONPATH=/app/mona_core

RUN chown -R app:app /app
USER app
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 CMD python -c "import shutil; import subprocess; import sys; sys.exit(0 if shutil.which('celery') else 1)" || exit 1
CMD ["celery", "-A", "celery_conf", "worker", "--loglevel=info"]
