# ---------- Build ----------
FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

COPY frontend .
RUN npm run build


# ---------- Runtime ----------
FROM nginxinc/nginx-unprivileged:stable-alpine


COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html


# Explicit for Checkov CKV_DOCKER_3
USER 101


EXPOSE 8080


# Explicit for Checkov CKV_DOCKER_2
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD nginx -t || exit 1


CMD ["nginx", "-g", "daemon off;"]
