---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mona-fastapi
spec:
  replicas: {{ .Values.fastapi.replicas }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.fastapi.service.targetPort }}"
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c']
          args:
            - |
              until nc -z -w 2 postgres {{ .Values.postgres.service.port }}; do
                echo "Waiting for PostgreSQL...";
                sleep 2;
              done;
              echo "PostgreSQL is available!"
        - name: alembic-upgrade
          image: "{{ .Values.images.fastapi.repository }}:{{ .Values.images.fastapi.tag }}"
          imagePullPolicy: {{ .Values.images.fastapi.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              value: {{ .Values.fastapi.env.DATABASE_URL | quote }}

      containers:
        - name: fastapi
          image: "{{ .Values.images.fastapi.repository }}:{{ .Values.images.fastapi.tag }}"
          imagePullPolicy: {{ .Values.images.fastapi.pullPolicy }}
          ports:
            - containerPort: {{ .Values.fastapi.service.targetPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.fastapi.livenessProbe.httpGet.path }}
              port: {{ .Values.fastapi.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.fastapi.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.fastapi.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.fastapi.readinessProbe.httpGet.path }}
              port: {{ .Values.fastapi.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.fastapi.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.fastapi.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.fastapi.resources | nindent 12 }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.fastapi.env.DATABASE_URL | quote }}
            - name: REDIS_URL
              value: {{ include "mona.redisUrl" . | quote }}
            - name: ADMIN_USERNAMES
              value: {{ .Values.fastapi.env.ADMIN_USERNAMES | quote }}
            - name: ADMIN_PASSWORDS
              value: {{ .Values.fastapi.env.ADMIN_PASSWORDS | quote }}
            - name: USER_USERNAMES
              value: {{ .Values.fastapi.env.USER_USERNAMES | quote }}
            - name: USER_PASSWORDS
              value: {{ .Values.fastapi.env.USER_PASSWORDS | quote }}

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  type: {{ .Values.fastapi.service.type }}
  selector:
    app: fastapi
  # ports:
  #   - port: {{ .Values.fastapi.service.port }}
  #     targetPort: {{ .Values.fastapi.service.targetPort }}
  #     nodePort: {{ .Values.fastapi.service.nodePort }}
  ports:
  - name: http
    port: {{ .Values.fastapi.service.port }}
    targetPort: {{ .Values.fastapi.service.targetPort }}
    nodePort: {{ .Values.fastapi.service.nodePort }}
