---
{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-prometheus-config" .Release.Name | trunc 63 | trimSuffix "-" }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: {{ .Values.global.externalPcExporter.jobName | quote }}
        static_configs:
          - targets:
              - {{ printf "%s:%v" .Values.global.externalPcExporter.host .Values.global.externalPcExporter.port | quote }}
            labels:
              physical_pc: "true"
      - job_name: kubernetes-cluster
        kubernetes_sd_configs:
          - role: node
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
{{- end }}
